# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        from main import CustomLineEdit
        self.inputEdit = CustomLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputEdit.sizePolicy().hasHeightForWidth())
        self.inputEdit.setSizePolicy(sizePolicy)
        self.inputEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.inputEdit.setMaximumSize(QtCore.QSize(250, 30))
        self.inputEdit.setObjectName("inputEdit")
        self.horizontalLayout.addWidget(self.inputEdit)
        self.translateButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translateButton.sizePolicy().hasHeightForWidth())
        self.translateButton.setSizePolicy(sizePolicy)
        self.translateButton.setMaximumSize(QtCore.QSize(100, 30))
        self.translateButton.setObjectName("translateButton")
        self.horizontalLayout.addWidget(self.translateButton)
        self.autoDetectCheckBox = QtWidgets.QCheckBox(self.centralWidget)
        self.autoDetectCheckBox.setMaximumSize(QtCore.QSize(100, 30))
        self.autoDetectCheckBox.setChecked(True)
        self.autoDetectCheckBox.setObjectName("autoDetectCheckBox")
        self.horizontalLayout.addWidget(self.autoDetectCheckBox)
        self.fromComboBox = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromComboBox.sizePolicy().hasHeightForWidth())
        self.fromComboBox.setSizePolicy(sizePolicy)
        self.fromComboBox.setMaximumSize(QtCore.QSize(120, 30))
        self.fromComboBox.setObjectName("fromComboBox")
        self.horizontalLayout.addWidget(self.fromComboBox)
        self.swapLangsButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swapLangsButton.sizePolicy().hasHeightForWidth())
        self.swapLangsButton.setSizePolicy(sizePolicy)
        self.swapLangsButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("arrowupdown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.swapLangsButton.setIcon(icon1)
        self.swapLangsButton.setObjectName("swapLangsButton")
        self.horizontalLayout.addWidget(self.swapLangsButton)
        self.toComboBox = QtWidgets.QComboBox(self.centralWidget)
        self.toComboBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toComboBox.sizePolicy().hasHeightForWidth())
        self.toComboBox.setSizePolicy(sizePolicy)
        self.toComboBox.setMaximumSize(QtCore.QSize(120, 30))
        self.toComboBox.setObjectName("toComboBox")
        self.horizontalLayout.addWidget(self.toComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_1 = QtWidgets.QLabel(self.centralWidget)
        self.label_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.verticalLayout_5.addWidget(self.label_1)
        self.textEdit_1 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_1.setReadOnly(True)
        self.textEdit_1.setTabStopWidth(13)
        self.textEdit_1.setObjectName("textEdit_1")
        self.verticalLayout_5.addWidget(self.textEdit_1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setTabStopWidth(13)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_5.addWidget(self.textEdit_2)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setTabStopWidth(13)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_5.addWidget(self.textEdit_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_4.setReadOnly(True)
        self.textEdit_4.setTabStopWidth(13)
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_6.addWidget(self.textEdit_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_5.setReadOnly(True)
        self.textEdit_5.setTabStopWidth(13)
        self.textEdit_5.setObjectName("textEdit_5")
        self.verticalLayout_7.addWidget(self.textEdit_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 850, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuTranslator = QtWidgets.QMenu(self.menuBar)
        self.menuTranslator.setObjectName("menuTranslator")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuTranslator.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Translator"))
        self.translateButton.setText(_translate("MainWindow", "Translate"))
        self.autoDetectCheckBox.setText(_translate("MainWindow", "Auto detect"))
        self.label_1.setText(_translate("MainWindow", "Google Translate"))
        self.label_2.setText(_translate("MainWindow", "Yandex Translate"))
        self.label_3.setText(_translate("MainWindow", "Definitions"))
        self.label_4.setText(_translate("MainWindow", "Yandex Dictionary"))
        self.label_5.setText(_translate("MainWindow", "Multitran Dictionary"))
        self.menuTranslator.setTitle(_translate("MainWindow", "&Translator"))

